### ISSUE TITLE
bugfix: fix a bug with assigning a representative pet

### ISSUE THREAD

**Issue by llsrrll96** [ppp-team/my-petlog-server#108]
## 📌 Feature Issue
> 대표 반려동물 지정 버그 수정

## 📝 To-do
- [x] Guardian(집사) 도메인에 대표 지정 추가
- [x] 집사 도메인에서 로직 처리 
- [x] modify to delete pet logic

## ETC
> 도메인 변경에 따라 Q클래스 생성 관련 Gradle 작업 필요
