### ISSUE TITLE
Add Recomment API

### ISSUE THREAD

**Issue by thdefn** [ppp-team/my-petlog-server#133]
## 📌 Feature Issue
> add recomment API

## 📝 To-do
- [x] modify comment table
- [x] add create recomment endpoint
- [x] apply changes to comment retrieval api

## ETC
>
