### ISSUE TITLE
add pet subscription feature

### ISSUE THREAD

**Issue by thdefn** [ppp-team/my-petlog-server#139]
## 📌 Feature Issue
> add pet subscription feature

## 📝 To-do
- [x] add register subscription or remove subscription endpoint
- [x] add api for retrieving accounts that the user is subscribed to
- [x] add api for retrieving accounts that subscribe to the user

## ETC
>
