### ISSUE TITLE
add prevent notification duplication

### ISSUE THREAD

**Issue by llsrrll96** [ppp-team/my-petlog-server#150]
## 📌 Feature Issue
> add prevent diary Like duplication

## 📝 To-do
- [x] add prevent diary Like duplication
- [x] 본인 좋아요 알림 방지
- [x] 구독시 중복알림 방지

**Comment by thdefn** [comment]
혹시 이거 어떤 이슈인가요  ? diary like 은 자료구조 set 이라서 like duplication 이 없을듯합니다

**Comment by llsrrll96** [comment]
> 혹시 이거 어떤 이슈인가요 ? diary like 은 자료구조 set 이라서 like duplication 이 없을듯합니다

현재 구조에서 좋아요 누를 때마다 알림 데이터가 저장이 되어서 ,  좋아요 눌렀던 이력을 테이블에 저장해서 알림을 한번만 저장되게 하려고합니다.

**Comment by thdefn** [comment]
> > 혹시 이거 어떤 이슈인가요 ? diary like 은 자료구조 set 이라서 like duplication 이 없을듯합니다
> 
> 현재 구조에서 좋아요 누를 때마다 알림 데이터가 저장이 되어서 , 좋아요 눌렀던 이력을 테이블에 저장해서 알림을 한번만 저장되게 하려고합니다.

오 고도화 기능이군요 ! 👍
