### ISSUE TITLE
add function about auth and user service

### ISSUE THREAD

**Issue by llsrrll96** [ppp-team/my-petlog-server#176]
## 📌 Feature Issue
> add function about auth and user service

## 📝 To-do
- [x] modify email verification time to last 3 minutes
- [x] add Login Type property
- [x] 소셜로그인 시 기존 이메일 계정 중복막기
